### ISSUE TITLE
java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by chenyesheng** [mcxtzhang/ItemDecorationIndexBar#32]
错误信息：
java.lang.IllegalArgumentException: Comparison method violates its general contract!
                                                                                              at java.util.TimSort.mergeLo(TimSort.java:743)
                                                                                              at java.util.TimSort.mergeAt(TimSort.java:479)
                                                                                              at java.util.TimSort.mergeCollapse(TimSort.java:406)
                                                                                              at java.util.TimSort.sort(TimSort.java:210)
                                                                                              at java.util.TimSort.sort(TimSort.java:169)
                                                                                              at java.util.Arrays.sort(Arrays.java:2010)
                                                                                              at java.util.Collections.sort(Collections.java:1883)

报错位置：
IndexBarDataHelperImpl.java  93行
Collections.sort(datas, new Comparator<BaseIndexPinyinBean>() {
            @Override
            public int compare(BaseIndexPinyinBean lhs, BaseIndexPinyinBean rhs) {
                if (!lhs.isNeedToPinyin()) {
                    return 0;
                } else if (!rhs.isNeedToPinyin()) {
                    return 0;
                } else if (lhs.getBaseIndexTag().equals("#")) {
                    return 1;
                } else if (rhs.getBaseIndexTag().equals("#")) {
                    return -1;
                } else {
                    return lhs.getBaseIndexPinyin().compareTo(rhs.getBaseIndexPinyin());
                }
            }
        });

这是我获取手机通讯录，之后调用 mIndexBar.getDataHelper().sortSourceDatas(); 的时候报的错误

**Comment by Lok1n8** [comment]
你好 我也有这个问题 请问你解决了吗

**Comment by chenyesheng** [comment]
@sher-loki 应该是姓名有某些特殊字符导致的，我把特殊字符去掉再进行排序就可以了。

**Comment by kyo2001lee** [comment]
我也是这个错误，非常的频繁！！是游戏列表，没有特殊字符

**Comment by dengdaoyus** [comment]
已经解决！需要可以联系我 QQ：980322048

**Comment by h2oiswater** [comment]
@chenyesheng 可以参考我的PR
