### ISSUE TITLE
标签或者代码中为null时，或者“”时出这个错误

### ISSUE THREAD

**Issue by gavinYip** [mcxtzhang/ItemDecorationIndexBar#57]
标签或者代码中为null时，或者“”时出这个错误
`  <item></item>`
` <item>""</item>`
AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: com.mcxtzhang.itemdecorationindexbar, PID: 22865
                                                                                      java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=1
                                                                                          at java.lang.String.startEndAndLength(String.java:588)
                                                                                          at java.lang.String.substring(String.java:1475)
                                                                                          at com.mcxtzhang.indexlib.IndexBar.helper.IndexBarDataHelperImpl.fillInexTag(IndexBarDataHelperImpl.java:73)
                                                                                          at com.mcxtzhang.indexlib.IndexBar.helper.IndexBarDataHelperImpl.sortSourceDatas(IndexBarDataHelperImpl.java:90)
                                                                                          at com.mcxtzhang.indexlib.IndexBar.widget.IndexBar.initSourceDatas(IndexBar.java:360)
                                                                                          at com.mcxtzhang.indexlib.IndexBar.widget.IndexBar.setmSourceDatas(IndexBar.java:343)
                                                                                          at mcxtzhang.itemdecorationdemo.ui.WeChatActivity$1.run(WeChatActivity.java:101)
                                                                                          at android.os.Handler.handleCallback(Handler.java:733)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5016)
                                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
                                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by gavinYip** [comment]
解决一下
截取前判断一下长度，为0就放到特殊字母"#"中吧
@Override
    public IIndexBarDataHelper fillInexTag(List<? extends BaseIndexPinyinBean> datas) {
        if (null == datas || datas.isEmpty()) {
            return this;
        }
        int size = datas.size();
        for (int i = 0; i < size; i++) {
            BaseIndexPinyinBean indexPinyinBean = datas.get(i);
            if (indexPinyinBean.isNeedToPinyin()) {
                //以下代码设置城市拼音首字母
                String tagString = indexPinyinBean.getBaseIndexPinyin().toString();
                if (tagString.length() != 0) { //截取前判断长度
                    String substring = tagString.substring(0, 1);
                    if (substring.matches("[A-Z]")) {//如果是A-Z字母开头
                        indexPinyinBean.setBaseIndexTag(substring);
                    } else {//特殊字母这里统一用#处理
                        indexPinyinBean.setBaseIndexTag("#");
                    }
                } else {
                    indexPinyinBean.setBaseIndexTag("#");
                }
            }
        }
        return this;
    }
