### ISSUE TITLE
发现一个bug,通讯录数据更新布局会乱

### ISSUE THREAD

**Issue by douya40** [mcxtzhang/ItemDecorationIndexBar#7]
发现一个bug,通讯录数据更新，布局会乱

**Comment by mcxtzhang** [comment]
数据更新后，除了要通知adapter，
也要通知 indexBar：
        mIndexBar  .setmSourceDatas(mDatas);//设置数据源

**Comment by douya40** [comment]
class GoodFriendListFragment extends BaseLazyMainFragment implements HttpListener<JSONObject> {

    @BindView(R.id.text_title)
    TextView textTitle;
    @BindView(R.id.text_right)
    TextView textRight;
    @BindView(R.id.id_tool_bar)
    Toolbar idToolBar;
    private static final String TAG = "GoodFriendListFragment";
    private RecyclerView mRv;
    private RecyclerView.Adapter mAdapter;
    private LinearLayoutManager mManager;
    private List<CityBean> mDatas;

    private TitleItemDecoration mDecoration;

    /**
     * 右侧边栏导航区域
     */
    private IndexBar mIndexBar;

    /**
     * 显示指示器DialogText
     */
    private TextView mTvSideBarHint;
    private int pageNum=1;
    private FriendList  friinfo;
    public static GoodFriendListFragment newInstance() {
        Bundle args = new Bundle();
        GoodFriendListFragment fragment = new GoodFriendListFragment();
        fragment.setArguments(args);

        return fragment;
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.goodfriendlistfragment, container, false);
        ButterKnife.bind(this, view);
        textTitle.setText(R.string.hylb);
        initToolbarNav(idToolBar);
        initView(view);
        return view;
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

    }

    private void initView(View view) {
        EventBus.getDefault().register(this);
        mRv = (RecyclerView) view.findViewById(R.id.rv);
        mRv.setLayoutManager(mManager = new LinearLayoutManager(getActivity()));
        //initDatas();
//        String[] data ={"广东","北金","jackie","Jack","sam","Sam","广东","北金","jackie","Jack","sam","Sam","广东","北金","jackie","Jack","sam","Sam","广东","北金","jackie","Jack","sam","Sam"};
//        initDatas(data);
        //mDatas = new ArrayList<>();//测试为空或者null的情况 已经通过 2016 09 08
        //如果add两个，那么按照先后顺序，依次渲染。
        mRv.addItemDecoration(new DividerItemDecoration(getActivity(), DividerItemDecoration.VERTICAL_LIST));
        //使用indexBar
        mTvSideBarHint = (TextView) view.findViewById(R.id.tvSideBarHint);//HintTextView
        mIndexBar = (IndexBar) view.findViewById(R.id.indexBar);//IndexBar


    }
    @Override
    protected void initLazyView(@Nullable Bundle savedInstanceState) {

    }

    @Override
    protected void onEnterAnimationEnd(Bundle savedInstanceState) {
        getFriendList();
    }

    public void getFriendList(){
        Request<JSONObject> request = new FastJsonRequest(Constants.API.FRIENDLIST_CUSTOMERSERVICE, RequestMethod.POST);
        request.setCacheKey(Constants.API.FRIENDLIST_CUSTOMERSERVICE);// 这里的key是缓存数据的主键，默认是url，使用的时候要保证全局唯一，否则会被其他相同url数据覆盖。
        request.setCacheMode(CacheMode.REQUEST_NETWORK_FAILED_READ_CACHE);
        CallServer.getRequestInstance().add((BaseAppCompatActivity) getActivity(), FRIENDLIST, request, this, false, false);
    }
    @Override
    public void onSucceed(int what, Response<JSONObject> response) {
        try {
            if (what == FRIENDLIST) {
                BaseModel info = JSON.parseObject(response.get().toString(), BaseModel.class);
                if (info.getState() == Constants.SUCCEED) {
                    friinfo = JSON.parseObject(response.get().toString(), FriendList.class);
                    Log.e(TAG,response.get().toString());
                    showList(friinfo.getData());
                } else {
                    JBModel jbinfo = JSON.parseObject(response.get().toString(), JBModel.class);
                    ToastUtils.show(jbinfo.getData());
                }
            }
        } catch (Exception e) {
            JBModel jbinfo = JSON.parseObject(response.get().toString(), JBModel.class);
            ToastUtils.show(jbinfo.getData());
        }
    }



    @Override
    public void onFailed(int what, Response<JSONObject> response) {
        ((BaseAppCompatActivity) getActivity()).showMessageDialog(R.string.request_failed, response.getException().getMessage());
    }


    private void   showList(List<FriendList.DataBean> mDatas){

            mAdapter = new CityAdapter(getActivity(), mDatas);
            mRv.setAdapter(mAdapter);
            mRv.addItemDecoration(mDecoration = new TitleItemDecoration(getActivity(), mDatas));
            mIndexBar.setmPressedShowTextView(mTvSideBarHint)//设置HintTextView
                    .setNeedRealIndex(false)//设置需要真实的索引
                    .setmLayoutManager(mManager)//设置RecyclerView的LayoutManager
                    .setmSourceDatas(mDatas);//设置数据源

    }
    @Subscribe(threadMode = ThreadMode.MAIN) //在ui线程执行
    public void onDataSynEvent(BzEvent event) {
//        getFriendList();
    }
    @Override
    public void onDestroyView() {
        super.onDestroyView();
        EventBus.getDefault().unregister(this);
    }
}
接口请求完是通知adapter，
也要通知 indexBar：
mIndexBar .setmSourceDatas(mDatas);//设置数据源
showList（）这个方法负责更新，但是在请求数据很大还没有加载完，就按返回键，时候会崩溃

**Comment by douya40** [comment]
而且广播通知更新联系人，目前没有好的方法能直接修改某一个item，只能重新获取数据刷新列表发现布局会乱和第一次的布局有重合

**Comment by mcxtzhang** [comment]
请把错误log附上 。而且布局重合是指什么 我也不清楚。 你提供的信息相当有限。截图 log 都没有 我无法判断。。

**Comment by douya40** [comment]
java.lang.ArrayIndexOutOfBoundsException: length=40; index=-1

**Comment by douya40** [comment]
TitleItemDecoration 这个写的有问题

**Comment by douya40** [comment]
java.lang.ArrayIndexOutOfBoundsException: length=40; index=-1
	at java.util.ArrayList.get(ArrayList.java:310)
	at com.laima365.laimaemployee.ui.view.decoration.TitleItemDecoration.onDrawOver(TitleItemDecoration.java:133)
	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3597)
	at android.view.View.getDisplayList(View.java:13401)
	at android.view.View.getDisplayList(View.java:13443)
	at android.view.View.draw(View.java:14234)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
	at android.view.View.getDisplayList(View.java:13396)
	at android.view.View.getDisplayList(View.java:13443)
	at android.view.View.draw(View.java:14234)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
	at android.view.View.draw(View.java:14520)
	at android.view.View.getDisplayList(View.java:13401)
	at android.view.View.getDisplayList(View.java:13443)
	at android.view.View.draw(View.java:14234)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
	at android.view.View.getDisplayList(View.java:13396)
	at android.view.View.getDisplayList(View.java:13443)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
	at android.view.View.getDisplayList(View.java:13339)
	at android.view.View.getDisplayList(View.java:13443)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
	at android.view.View.getDisplayList(View.java:13339)
	at android.view.View.getDisplayList(View.java:13443)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
	at android.view.View.getDisplayList(View.java:13339)
	at android.view.View.getDisplayList(View.java:13443)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
	at android.view.View.getDisplayList(View.java:13339)
	at android.view.View.getDisplayList(View.java:13443)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
	at android.view.View.getDisplayList(View.java:13339)
	at android.view.View.getDisplayList(View.java:13443)
	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1606)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1481)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2479)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2343)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1966)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1058)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5973)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:787)
	at android.view.Choreographer.doCallbacks(Choreographer.java:600)
	at android.view.Choreographer.doFrame(Choreographer.java:569)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:773)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5314)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by douya40** [comment]
什么时候能更新修复呢

**Comment by mcxtzhang** [comment]
你把全部代码传给我，我找时间看一下吧，应该是你使用的问题，我在项目里多出使用到都没有出现这种情况
